In [127]:
import pandas as pd
import numpy as np
import math
import scipy.stats as si

In [128]:
datareader=pd.read_csv('netflix2.csv')
df=datareader

In [129]:

df.drop(['Open', 'High','Low','Adj Close'], axis=1, inplace=True)
del df['Volume']

In [130]:

df['Week'] = np.arange(len(df))

In [132]:

r=0.05848
K=370
sigma=.0994

In [133]:
df['T']=(df['Week']*(7)/(254))

In [134]:
df['d1']=((np.log(df['Close'])/K)+(r+(.5*sigma*sigma))*(df['T']))/(sigma*np.sqrt(df['T']))

In [135]:
df['d1']=((np.log((df['Close'])/K)+(r+(.5*sigma*sigma))*(df['T'])))/((sigma*np.sqrt(df['T'])))

In [136]:
df['d2']=df['d1']-sigma*np.sqrt(df['T'])

In [137]:
df['Call_price']=(df['Close']*si.norm.cdf(df['d1'],0.0,1.0))-(K*np.exp(-r*df['T'])*si.norm.cdf(df['d2'],0.0,1.0))

In [138]:
df['delta']=si.norm.cdf(df['d1'],0.0,1.0)

In [139]:
df['Number of stocks']=np.ceil(df['delta']*1000)

In [140]:
df['Received']=df['Call_price']*1000

In [141]:
df['Shares Bought']=df['Number of stocks']*((df['Close']).shift(1))

In [142]:
df['Borrowing']=df['Shares Bought']-df['Received']

In [143]:
df

,Date,Close,Week,T,d1,d2,Call_price,delta,Number of stocks,Received,Shares Bought,Borrowing
0,2020-01-06,335.829987,0,0.000000,-inf,-inf,0.000000e+00,0.000000e+00,0.0,0.000000e+00,NaN,NaN
1,2020-01-07,330.750000,1,0.027559,-6.689916,-6.706417,8.720612e-12,1.116497e-11,1.0,8.720612e-09,335.829987,335.829987
2,2020-01-08,339.260010,2,0.055118,-3.566988,-3.590324,3.520410e-04,1.805539e-04,1.0,3.520410e-01,330.750000,330.397959
3,2020-01-09,335.660004,3,0.082677,-3.224537,-3.253118,1.610470e-03,6.308838e-04,1.0,1.610470e+00,339.260010,337.649540
4,2020-01-10,329.049988,4,0.110236,-3.342222,-3.375225,1.166835e-03,4.155522e-04,1.0,1.166835e+00,335.660004,334.493169
...,...,...,...,...,...,...,...,...,...,...,...,...
78,2020-04-28,403.829987,78,2.149606,1.535790,1.390054,7.922055e+01,9.377051e-01,938.0,7.922055e+04,395254.444690,316033.890880
79,2020-04-29,411.890015,79,2.177165,1.672699,1.526032,8.737109e+01,9.528067e-01,953.0,8.737109e+04,384849.977611,297478.887837
80,2020-04-30,419.850006,80,2.204724,1.803743,1.656151,9.553260e+01,9.643642e-01,965.0,9.553260e+04,397473.864475,301941.266347
81,2020-05-01,415.269989,81,2.232283,1.730486,1.581975,9.165783e+01,9.582283e-01,959.0,9.165783e+04,402636.155754,310978.327599
82,2020-05-04,428.149994,82,2.259843,1.936013,1.786587,1.046329e+02,9.735669e-01,974.0,1.046329e+05,404472.969286,299840.083158

In [144]:

df.loc[2:,'Borrowing'] =df['Borrowing'].shift(1)*(np.exp(r*df['T']))+(df['Number of stocks']-df['Number of stocks'].shift(1))*df['Call_price']

In [145]:
df['Received'][2:]=0
df['Shares Bought'][2:]=0

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [146]:
df

,Date,Close,Week,T,d1,d2,Call_price,delta,Number of stocks,Received,Shares Bought,Borrowing
0,2020-01-06,335.829987,0,0.000000,-inf,-inf,0.000000e+00,0.000000e+00,0.0,0.000000e+00,NaN,NaN
1,2020-01-07,330.750000,1,0.027559,-6.689916,-6.706417,8.720612e-12,1.116497e-11,1.0,8.720612e-09,335.829987,335.829987
2,2020-01-08,339.260010,2,0.055118,-3.566988,-3.590324,3.520410e-04,1.805539e-04,1.0,0.000000e+00,0.000000,336.914217
3,2020-01-09,335.660004,3,0.082677,-3.224537,-3.253118,1.610470e-03,6.308838e-04,1.0,0.000000e+00,0.000000,331.999288
4,2020-01-10,329.049988,4,0.110236,-3.342222,-3.375225,1.166835e-03,4.155522e-04,1.0,0.000000e+00,0.000000,339.833268
...,...,...,...,...,...,...,...,...,...,...,...,...
78,2020-04-28,403.829987,78,2.149606,1.535790,1.390054,7.922055e+01,9.377051e-01,938.0,0.000000e+00,0.000000,355518.338134
79,2020-04-29,411.890015,79,2.177165,1.672699,1.526032,8.737109e+01,9.528067e-01,953.0,0.000000e+00,0.000000,360255.894411
80,2020-04-30,419.850006,80,2.204724,1.803743,1.656151,9.553260e+01,9.643642e-01,965.0,0.000000e+00,0.000000,339562.266891
81,2020-05-01,415.269989,81,2.232283,1.730486,1.581975,9.165783e+01,9.582283e-01,959.0,0.000000e+00,0.000000,343496.425912
82,2020-05-04,428.149994,82,2.259843,1.936013,1.786587,1.046329e+02,9.735669e-01,974.0,0.000000e+00,0.000000,356484.667179